DROP TABLE #TEMP_PARCELAS;

go

WITH Split_Data AS (
    SELECT 
        CONTRATO,
		VALOR_DO_ACORDO,
	    DATA_Insert,
        IF_PARCELAS,
        CAST('<X>' + REPLACE(IF_PARCELAS, ',', '</X><X>') + '</X>' AS XML) AS XMLData
    FROM TB_ACORDO_EASYCOLETOR
    WHERE EASY_CONTRATO NOT IN (SELECT EASY_CONTRATO FROM TB_PARCELA_ACORDO)
    AND STATUS_PAGAMENTO is null 
    AND ISNULL(IF_PARCELAS,'') <> ''
)
SELECT 
    CONTRATO,
	VALOR_DO_ACORDO,
	DATA_Insert,
    RTRIM(LTRIM(Split.value('.', 'VARCHAR(20)'))) AS PARCELA
INTO #TEMP_PARCELAS
FROM Split_Data
CROSS APPLY XMLData.nodes('/X') AS Tbl(Split)
ORDER BY CONTRATO, PARCELA


SELECT DUPCLAS,DUPCONT, DUPORDE, CASE WHEN DUPVRTI = VALOR_DO_ACORDO + DUPRECANTE THEN 'APTO' ELSE 'INAPTO' END AS RealizarBaixa, 
 VALOR_DO_ACORDO, DUPVRTI, DUPVRPG, DUPRECANTE
FROM #TEMP_PARCELAS 
INNER JOIN FACTBDUP ON DUPCONT = CONTRATO AND DUPORDE = PARCELA
ORDER BY DATA_Insert DESC



